scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi-local'
    scrape_interval: 5s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: 'fastapi-remote'
    scrape_interval: 15s
    scheme: https
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['auth-service-g7nh.onrender.com']
